#!/bin/bash

defaults write org.videolan.vlc recentlyPlayedMedia ''
defaults write org.videolan.vlc recentlyPlayedMediaList ''
defaults write com.apple.NetAuthAgent PreviouslySelectedShares ''
defaults read | grep good
