#! /usr/bin/env python
# -*- coding: utf-8 -*-

import os
from os.path import join

print("""
       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
       !!                                               !!
       !! Flatten files of current folder, recursively. !!
       !! .eg. moves all files under all sub-folders to !!
       !! current folder.                               !!
       !!                                               !!
       !!    NOTICE! this might MESS UP your files!     !!
       !!                                               !!
       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
""")


secret = input("Enter 123abc to continue:")

if secret != "123abc":
    print("you Entered " + secret, ", WRONG answer!")
    print("Aborted!!!")
    import sys
    sys.exit()


for root, dirs, files in os.walk('.'):
    if root == ".":
        continue
    for file in files:
        cmd = 'mv "' + join(root, file) + '" "' + file + '"'
        print(cmd)
        os.system(cmd)


for folder in os.listdir('.'):
    if not os.path.isdir(folder):
        continue
    cmd = "rm -rf " + folder
    print(cmd)
    os.system(cmd)
