#! /usr/bin/env python3
# -*- coding: utf-8 -*-

"""
folders - a script to dump folders based on regular expression match

Commands:

    folders
        - list all the files under current dir recursively, including sub folders

    folders "*py$"
        - same as first one + filter the whole folder path with r'.*py$'

    folders s*.py /Users/realfun/
        - same as 2nd one + search in folder /Users/realfun/

"""

import os
from os import path
import sys
import re


def wildchar_to_regex(wildchar):
    if not wildchar:
        return ''
    return wildchar.replace('.', '\\.').replace('*', '.*').replace('?', '.?')


def main():
    workdir = os.getcwd()
    pattern = ".*"
    if len(sys.argv) > 1:
        pattern = wildchar_to_regex(sys.argv[1])
    if len(sys.argv) > 2:
        workdir = sys.argv[2]

    for root, dirs, _ in os.walk(workdir):
        paths = [path.join(root, dir, "") for dir in dirs]
        for full_path in paths:
            if re.search(wildchar_to_regex(pattern), full_path):
                print(full_path)


main()
